import { defineNuxtModule, addComponent, createResolver } from '@nuxt/kit'

export default defineNuxtModule({
  meta: {
    name: 'lucide-icons',
    configKey: 'lucideIcons',
  },
  setup(_options, nuxt) {
    const { resolve } = createResolver(import.meta.url)

    // 自动导入常用图标
    const icons = [
      'Plus', 'Minus', 'X', 'Check', 'ChevronDown', 'ChevronUp', 'ChevronLeft', 'ChevronRight',
      'Search', 'Menu', 'MoreHorizontal', 'MoreVertical',
      'Settings', 'Home', 'User', 'LogOut', 'LogIn',
      'MessageSquare', 'MessageCircle', 'Send', 'Edit', 'Trash', 'Trash2',
      'Copy', 'CheckCircle', 'XCircle', 'AlertCircle', 'Info',
      'Sun', 'Moon', 'Monitor', 'Globe',
      'Download', 'Upload', 'Share', 'ExternalLink',
      'RefreshCw', 'RotateCcw', 'Clock', 'Calendar',
      'Folder', 'File', 'FileText', 'Image', 'Video', 'Music',
      'Mail', 'Bell', 'Bookmark', 'Star', 'Heart',
      'ThumbsUp', 'ThumbsDown', 'Eye', 'EyeOff',
      'Lock', 'Unlock', 'Key', 'Shield',
      'Camera', 'Mic', 'MicOff', 'Volume2', 'VolumeX',
      'Play', 'Pause', 'Stop', 'SkipForward', 'SkipBack',
      'Wifi', 'Bluetooth', 'Airplay', 'Cast',
      'Map', 'MapPin', 'Navigation', 'Compass',
      'Box', 'Boxes', 'Package', 'Archive',
      'Tag', 'Tags', 'Ticket', 'Gift',
      'CreditCard', 'DollarSign', 'TrendingUp', 'TrendingDown',
      'Activity', 'Zap', 'Cpu', 'Database', 'Server',
      'Cloud', 'CloudRain', 'CloudSnow', 'CloudLightning',
      'Sunrise', 'Sunset', 'Cloudy', 'Wind',
      'Book', 'BookOpen', 'GraduationCap', 'Award',
      'Briefcase', 'Tool', 'Hammer', 'Wrench', 'Screwdriver',
      'ShoppingCart', 'ShoppingBag', 'Store', 'Tag',
      'Phone', 'Smartphone', 'Tablet', 'Laptop', 'Monitor',
      'Tv', 'Radio', 'Headphones', 'Speaker',
      'Grid', 'List', 'Layout', 'Columns', 'PanelLeft', 'PanelRight',
      'PanelLeftClose', 'PanelRightClose', 'Sidebar',
      'Maximize', 'Minimize', 'Expand', 'Shrink',
      'Move', 'DragHandle', 'Crop', 'Scissors',
      'Filter', 'Sliders', 'ToggleLeft', 'ToggleRight',
      'ChevronsLeft', 'ChevronsRight', 'ChevronsUp', 'ChevronsDown',
      'ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown',
      'ArrowLeftRight', 'ArrowUpDown', 'CornerDownLeft', 'CornerDownRight',
      'Hash', 'Asterisk', 'AtSign', 'Percent',
      'Bold', 'Italic', 'Underline', 'Strikethrough',
      'Type', 'AlignLeft', 'AlignCenter', 'AlignRight', 'AlignJustify',
      'Indent', 'Outdent', 'Quote', 'Code',
      'Link', 'Unlink', 'ExternalLink',
      'Image', 'ImagePlus', 'ImageMinus',
      'Video', 'VideoOff', 'VideoPlus',
      'Music', 'Music2', 'Music3', 'Music4',
      'Play', 'Pause', 'Stop', 'SkipForward', 'SkipBack',
      'Repeat', 'Shuffle',
      'Bot', 'Robot', 'Brain', 'Sparkles',
      'Inbox', 'Archive', 'Box', 'Package',
      'Pin', 'PinOff', 'Flag', 'FlagOff',
      'HelpCircle', 'HelpSquare', 'QuestionMark',
      'Circle', 'Square', 'Triangle', 'Hexagon',
      'Star', 'Heart', 'Diamond', 'Gem',
      'Smile', 'Frown', 'Meh', 'Laugh',
      'Hand', 'ThumbsUp', 'ThumbsDown', 'HandMetal',
      'Users', 'UserCheck', 'UserPlus', 'UserMinus', 'UserX',
      'Group', 'Network', 'Share2', 'Share3',
      'MessageSquare', 'MessageCircle', 'Mail', 'Send',
      'Inbox', 'Archive', 'Box', 'Package',
      'Calendar', 'Clock', 'Watch', 'Timer',
      'Alarm', 'AlarmCheck', 'AlarmMinus', 'AlarmPlus',
      'Bell', 'BellOff', 'BellRing', 'Notification',
      'AlertTriangle', 'AlertCircle', 'AlertOctagon',
      'CheckCircle', 'CheckSquare', 'XCircle', 'XSquare',
      'HelpCircle', 'HelpSquare', 'Info', 'XOctagon',
      'Loader', 'Loader2', 'RefreshCw', 'RefreshCcw',
      'RotateCw', 'RotateCcw', 'Move', 'MoveDiagonal',
      'Maximize', 'Maximize2', 'Minimize', 'Minimize2',
      'Focus', 'Crosshair', 'Target', 'Radar',
      'Aperture', 'Camera', 'CameraOff', 'Image',
      'Film', 'Tv', 'Monitor', 'Smartphone', 'Tablet',
      'Laptop', 'MonitorPlay', 'MonitorPause', 'MonitorStop',
      'Power', 'Plug', 'Battery', 'BatteryCharging',
      'Wifi', 'WifiOff', 'Signal', 'SignalZero',
      'Bluetooth', 'BluetoothConnected', 'BluetoothSearching', 'BluetoothOff',
      'HardDrive', 'Database', 'Server', 'Cloud',
      'Download', 'DownloadCloud', 'Upload', 'UploadCloud',
      'File', 'FileText', 'FileType', 'Folder',
      'FolderOpen', 'Archive', 'Box', 'Package',
      'Tag', 'Tags', 'Bookmark', 'BookmarkPlus',
      'Star', 'StarOff', 'Heart', 'HeartOff',
      'ThumbsUp', 'ThumbsDown', 'Hand', 'Fingerprint',
      'Eye', 'EyeOff', 'View', 'Glasses',
      'Search', 'ZoomIn', 'ZoomOut', 'Scan',
      'QrCode', 'Barcode', 'ScanLine', 'Nfc',
    ]

    icons.forEach(icon => {
      addComponent({
        name: `Icon${icon}`,
        export: icon,
        filePath: 'lucide-vue-next',
      })
    })
  },
})
